name: kavi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  collection: ^1.19.1
  meta: ^1.16.0
  # OpenAI SDK for Dart (unofficial)
  dart_openai: ^5.1.0
  # HTTP for manual providers if needed
  http: ^1.2.2
  shared_preferences: ^2.5.3
  flutter_markdown: ^0.7.7+1
  dart_mcp: ^0.3.3
  file_picker: ^10.3.1
  gpt_markdown: ^1.1.2
  # Ollama client for Dart
  ollama_dart: ^0.2.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  freezed: ^3.2.0
  # Additional testing dependencies for comprehensive unit tests
  mockito: ^5.4.4
  test: ^1.25.8
  faker: ^2.2.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
